# Generated by Django 6.0.3 on 2026-04-08 07:19

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "prod_type",
                    models.CharField(
                        choices=[
                            ("Shoe", "Shoe"),
                            ("Sandals", "Sandals"),
                            ("Sneackers", "Sneackers"),
                            ("Ugi", "Ugi"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Boy", "Boy"),
                            ("Girl", "Girl"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("country", models.CharField(max_length=60)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("Winter", "Winter"),
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Autumn", "Autumn"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[
                            (19, "Newborn_19"),
                            (20, "Newborn_20"),
                            (21, "Newborn_21"),
                            (22, "Newborn_22"),
                            (23, "preschool_23"),
                            (24, "preschool_24"),
                            (25, "preschool_25"),
                            (26, "preschool_26"),
                            (27, "preschool_27"),
                            (28, "elementary_28"),
                        ]
                    ),
                ),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=shop.models.image_converter
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="shop.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.vendor"
            ),
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.wishlist",
                    ),
                ),
            ],
            options={
                "unique_together": {("wishlist", "product")},
            },
        ),
        migrations.AddField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                through="shop.WishlistItem", to="shop.product"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("vendor", "model_name", "size")},
        ),
    ]
