# Generated by Django 6.0.3 on 2026-04-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="full_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="country",
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Boy", "Boy"),
                    ("Girl", "Girl"),
                    ("Unisex", "Unisex"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="season",
            field=models.CharField(
                choices=[
                    ("Winter", "Winter"),
                    ("Summer", "Summer"),
                    ("Demiseason", "Demiseason"),
                    ("Flease Demiseason", "Fleasedimeseason"),
                ],
                max_length=25,
            ),
        ),
    ]
