# Generated by Django 6.0.3 on 2026-04-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_price_product_full_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Boy", "Boy"),
                    ("Girl", "Girl"),
                    ("Unisex", "Unisex"),
                    ("Unknown", "Unknown"),
                ],
                default="Unknown",
                max_length=10,
            ),
        ),
    ]
