# Generated by Django 6.0.3 on 2026-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shop",
            "0004_order_status_order_total_price_alter_orderitem_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boy", "Boy"),
                    ("girl", "Girl"),
                    ("unisex", "Unisex"),
                ],
                default="unisex",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
