# Generated by Django 6.0.3 on 2026-04-10 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_updated_at_alter_product_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('Shoe', 'Shoe'), ('Sandals', 'Sandals'), ('Sneakers', 'Sneakers'), ('Ugi', 'Ugi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Demiseason', 'Demiseason'), ('Flease Demiseason', 'Fleasedemiseason')], max_length=25),
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_full_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введіть номер у форматі +380XXXXXXXXX', regex='^\\+380\\d{9}$')])),
                ('delivery_type', models.CharField(choices=[('np_warehouse', 'НоваПошта: Відділення'), ('np_postamat', 'НоваПошта: Поштомат'), ('np_address', 'НоваПошта: Адресна доставка')], default='np_warehouse', max_length=20)),
                ('city_name', models.CharField(max_length=255)),
                ('city_ref', models.CharField(blank=True, max_length=36)),
                ('warehouse_address', models.CharField(blank=True, max_length=500)),
                ('warehouse_ref', models.CharField(blank=True, max_length=36)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('building_number', models.CharField(blank=True, max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=14)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='shop.order')),
            ],
        ),
    ]
