# Generated by Django 6.0.3 on 2026-04-16 07:45

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_season_alter_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'model_name')},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.image_converter),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(19, 'Newborn_19'), (20, 'Newborn_20'), (21, 'Newborn_21'), (22, 'Newborn_22'), (23, 'preschool_23'), (24, 'preschool_24'), (25, 'preschool_25'), (26, 'preschool_26'), (27, 'preschool_27'), (28, 'elementary_28')])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product')),
            ],
            options={
                'ordering': ['size'],
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.productsize'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productsize'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_size')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
