# Generated by Django 6.0.3 on 2026-04-17 07:23

import django.core.validators
import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_orderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Позиція кошика', 'verbose_name_plural': 'Позиції кошика'},
        ),
        migrations.AlterModelOptions(
            name='deliveryinfo',
            options={'verbose_name': 'Інформація про доставку', 'verbose_name_plural': 'Інформація про доставку'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиція замовлення', 'verbose_name_plural': 'Позиції замовлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size'], 'verbose_name': 'Розмір товару', 'verbose_name_plural': 'Розміри товарів'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Список бажань', 'verbose_name_plural': 'Списки бажань'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Товар у списку бажань', 'verbose_name_plural': 'Товари у списку бажань'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.cart', verbose_name='Кошик'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.productsize', verbose_name='Розмір товару'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер будинку'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='city_name',
            field=models.CharField(max_length=255, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='city_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Ref міста (НП)'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_type',
            field=models.CharField(choices=[('np_warehouse', 'Нова Пошта: Відділення'), ('np_postamat', 'Нова Пошта: Поштомат'), ('np_address', 'Нова Пошта: Адресна доставка')], default='np_warehouse', max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='shop.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='recipient_full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ отримувача'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='recipient_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введіть номер у форматі +380XXXXXXXXX', regex='^\\+380\\d{9}$')], verbose_name='Телефон отримувача'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=14, verbose_name='Номер відстеження'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='warehouse_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адреса відділення'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='warehouse_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Ref відділення (НП)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікується'), ('processing', 'В обробці'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Загальна сума (грн)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.productsize', verbose_name='Розмір товару'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1100, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Повна ціна (грн)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'Хлопчик'), ('girl', 'Дівчинка'), ('unisex', 'Унісекс')], default='unisex', max_length=10, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.image_converter, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.CharField(max_length=100, verbose_name='Назва моделі'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('Shoe', 'Черевики'), ('Sandals', 'Сандалі'), ('Sneakers', 'Кросівки/Кеди'), ('Ugi', 'Угі')], max_length=20, verbose_name='Тип товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('Winter', 'Зима'), ('Summer', 'Літо'), ('Demiseason', 'Демісезон'), ('Fleece Demiseason', 'Демісезон флісовий')], max_length=25, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor', verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(choices=[(19, 'Новонароджений 19'), (20, 'Новонароджений 20'), (21, 'Новонароджений 21'), (22, 'Новонароджений 22'), (23, 'Дошкільний 23'), (24, 'Дошкільний 24'), (25, 'Дошкільний 25'), (26, 'Дошкільний 26'), (27, 'Дошкільний 27'), (28, 'Шкільний 28')], verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(through='shop.WishlistItem', to='shop.product', verbose_name='Товари'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.wishlist', verbose_name='Список бажань'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.gallery_image_converter, verbose_name='Зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['-is_main', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=shop.models.video_converter, verbose_name='Відео файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Назва відео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Відео товару',
                'verbose_name_plural': 'Відео товарів',
                'ordering': ['order', 'id'],
            },
        ),
    ]
