# Generated by Django 6.0.3 on 2026-05-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.productsize', verbose_name='Розмір товару'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop.productsize', verbose_name='Розмір товару'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'Хлопчик'), ('girl', 'Дівчинка'), ('unisex', 'Хлопчик/Дівчинка')], default='unisex', max_length=10, verbose_name='Стать'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(choices=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44')], verbose_name='Розмір'),
        ),
    ]
