# Generated by Django 6.0.3 on 2026-05-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cart_options_alter_cartitem_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
