# Generated by Django 6.0.3 on 2026-05-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card_online", "Карткою онлайн"),
                    ("cod", "Оплата у відділенніпри отриманні товару"),
                    ("baby_package", "Карткою 'Пакунок малюка'"),
                    ("school_package", "Карткою 'Пакунок школяра'"),
                    ("bank_transfer", "Оплата за реквізитами"),
                ],
                default="cod",
                max_length=20,
                verbose_name="Спосіб оплати",
            ),
        ),
    ]
