# Generated by Django 6.0.3 on 2026-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('fixed', 'Фіксована сума'), ('percent', 'Відсоток')], max_length=10, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розмір знижки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мін. сума замовлення')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Діє до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. використань')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Використано')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка (грн)'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промокод'),
        ),
    ]
