# Generated by Django 6.0.3 on 2026-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_payment_and_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='delivery_type',
            field=models.CharField(choices=[('np_warehouse', 'Нова Пошта: Відділення'), ('np_postamat', 'Нова Пошта: Поштомат'), ('np_address', 'Нова Пошта: Адресна доставка'), ('pickup', 'Самовивіз з магазину')], default='np_warehouse', max_length=20, verbose_name='Тип доставки'),
        ),
    ]
