# Generated by Django 6.0.3 on 2026-05-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_add_pickup_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Детальний опис (SEO)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1100, null=True, verbose_name='Короткий опис'),
        ),
    ]
