# Generated by Django 6.0.3 on 2026-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_add_sitevisit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "ordering": ["name"],
                "verbose_name": "Виробник",
                "verbose_name_plural": "Виробники",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="seo_h1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SEO H1"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="SEO заголовок",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Назва бренду"
            ),
        ),
    ]
