# Generated by Django 6.0.3 on 2026-06-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_alter_vendor_options_product_seo_h1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Slug"
            ),
        ),
    ]
