# Generated by Django 6.0.3 on 2026-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="prod_type",
            field=models.CharField(
                choices=[
                    ("Shoe", "Черевики"),
                    ("Sandals", "Сандалі"),
                    ("Sneakers", "Кросівки"),
                    ("Ugi", "Угі"),
                ],
                max_length=20,
                verbose_name="Тип товару",
            ),
        ),
    ]
