# Generated by Django 6.0.3 on 2026-06-25 09:54

from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    Product = apps.get_model("shop", "Product")

    for product in Product.objects.filter(slug__isnull=True):
        slug = slugify(
            f"{product.vendor.name}-{product.model_name}", allow_unicode=True
        )

        base = slug
        counter = 1

        while Product.objects.filter(slug=slug).exists():
            slug = f"{base}-{counter}"
            counter += 1

        product.slug = slug
        product.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_alter_product_prod_type"),
    ]

    operations = [
        migrations.RunPython(fill_slugs),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=255,
                blank=True,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
