# Generated by Django 6.0.3 on 2026-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_alter_product_prod_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
